# Generated by Django 5.1.6 on 2026-02-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='default_user', max_length=100)),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('start_datetime', models.DateTimeField(verbose_name='開始日時')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('event_type', models.CharField(choices=[('activity', 'アクティビティ'), ('block', 'ブロック期間'), ('deadline', '締切')], default='activity', max_length=20, verbose_name='種別')),
                ('priority', models.IntegerField(choices=[(1, '最重要'), (2, '重要'), (3, '普通'), (4, '低'), (5, '最低')], default=3, verbose_name='優先度')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='終日イベント')),
                ('category', models.CharField(blank=True, help_text='例: テスト、会議、デート、勉強', max_length=50, null=True, verbose_name='カテゴリ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'イベント',
                'verbose_name_plural': 'イベント',
                'db_table': 'events',
                'ordering': ['start_datetime'],
            },
        ),
    ]
