# Generated by Django 5.1.6 on 2026-02-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.JSONField(blank=True, default=list, verbose_name='カテゴリ'),
        ),
    ]
